Do not cast keys to string via str formatting
It turns out that using such valid keys as tuples do not play properly
with old string formatting:

    >>> raise KeyError("'%s'" % (42, 'foo'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: not all arguments converted during string formatting

The proper solution will be to use a key "As Is" and let KeyError to
cast its arguments to strings.